In [ ]:
import pandas as pd
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    pipeline,
    BitsAndBytesConfig
)
import torch
import json
from tqdm import tqdm

In [ ]:
model_name='granite'
model_path='/data/jfraile/llms/granite-3.3-2b-instruct'

In [4]:
model= AutoModelForCausalLM.from_pretrained(model_path, device_map='auto', torch_dtype=torch.bfloat16, trust_remote_code=True).eval()
tokenizer = AutoTokenizer.from_pretrained(model_path)

Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  2.13it/s]

In [ ]:
def interact_with_model(prompt, max_tokens=500):
    pipeline1 = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    )

    pipeline_kwargs = {
        "do_sample": True,
        "temperature": 0.75,
        "max_new_tokens": max_tokens,
        "return_full_text": False
    }
    chat=[{'role':'user', 'content':prompt}]
    final_prompt=tokenizer.apply_chat_template(chat, tokenize=False)
    pipeline_kwargs=pipeline_kwargs
    pipeline_kwargs['eos_token_id']=tokenizer.eos_token_id
    for out in pipeline1(final_prompt,**pipeline_kwargs):
        model_out=out['generated_text']
    return model_out

# Dipromats

In [ ]:
def load_annotations():
    path=f'/data/jfraile/Programs/datasets/DIPROMATS_2024_T2/dipromats24_t2_train_es.json'
    with open(path, 'r') as file:
        data=json.load(file)
        data=data['dataset']
        df_es=pd.DataFrame(data)

        country_columns = {
            "China": [f"CH{i}" for i in range(1, 7)],
            "Russia": [f"RU{i}" for i in range(1, 7)],
            "EU": [f"EU{i}" for i in range(1, 7)],
            "USA": [f"US{i}" for i in range(1, 7)],
        }

        for idx, row in df_es.iterrows():
            country = row["country"]
            country_narratives = country_columns.get(country, [])
            
            for i, narrative in enumerate(country_narratives, start=1):
                df_es.loc[idx, f"N{i}"] = row[narrative]

        df_es.drop(columns=[col for cols in country_columns.values() for col in cols], inplace=True)

    path=f'/data/jfraile/Programs/datasets/DIPROMATS_2024_T2/dipromats24_t2_train_en.json'
    with open(path, 'r') as file:
        data=json.load(file)
        narratives=data['narratives']
        data=data['dataset']
        df_en=pd.DataFrame(data)
        country_columns = {
            "China": [f"CH{i}" for i in range(1, 7)],
            "Russia": [f"RU{i}" for i in range(1, 7)],
            "EU": [f"EU{i}" for i in range(1, 7)],
            "USA": [f"US{i}" for i in range(1, 7)],
        }

        for idx, row in df_en.iterrows():
            country = row["country"]
            country_narratives = country_columns.get(country, [])
            
            for i, narrative in enumerate(country_narratives, start=1):
                df_en.loc[idx, f"N{i}"] = row[narrative]

        df_en.drop(columns=[col for cols in country_columns.values() for col in cols], inplace=True)
    
    df_train=pd.concat([df_es, df_en], ignore_index=True)
    columns=['tweet_id', 'text', 'country', 'N1', 'N2', 'N3', 'N4', 'N5', 'N6']
    df_train=df_train[columns]
    narratives=pd.DataFrame(narratives)
    narratives['country']=narratives['country'].map({'China':'China', 'Russia':'Russia', 'European Union':'EU', 'USA':'USA'})
    return df_train, narratives

def write_examples(examples):
    t="""
	
"""
    for ex in examples:
        ex=ex.replace("\n", " ")
        t=t+f"\t- {ex} \n"
    return t

In [7]:
df, narratives=load_annotations()

# Dipromats Description from titles

In [8]:
def get_prompt(country_id, title):
    if country_id=='USA':
        country='United States of America'
    elif country_id=='EU':
        country='European Union'
    else:
        country=country_id

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title of a narrative about {country}. You also have to take into account the social, political and cultural context because the tweets were written throughout the year 2020. Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the narrative. Your description will have to help improve the identification of narratives in tweets.


Narrative title: {title} 

Task: Generate a description of the narrative. 
    """
    return user_prompt

In [9]:
df_results=pd.DataFrame(columns=['narrative', 'result'])
for i in tqdm(range(len(narratives))):
    nar=narratives.iloc[i]
    country=nar['country']
    title=nar['title']
    n=nar['n_id'][-1]
    description=nar['description']
    dft=df[(df['country'] == country) & (df[f'N{n}'] != 'no')]
    examples=dft['text'].values
    prompt=get_prompt(country, title)
    result=interact_with_model(prompt)
    new_row = pd.DataFrame({'narrative': [nar['n_id']], 'result': [result]})
    df_results = pd.concat([df_results, new_row], ignore_index=True)

  0%|          | 0/24 [00:00<?, ?it/s]Device set to use cuda:0
  4%|▍         | 1/24 [00:05<02:04,  5.41s/it]Device set to use cuda:0
  8%|▊         | 2/24 [00:11<02:09,  5.88s/it]Device set to use cuda:0
 12%|█▎        | 3/24 [00:17<02:02,  5.82s/it]Device set to use cuda:0
 17%|█▋        | 4/24 [00:22<01:47,  5.37s/it]Device set to use cuda:0
 21%|██        | 5/24 [00:28<01:52,  5.92s/it]Device set to use cuda:0
 25%|██▌       | 6/24 [00:35<01:51,  6.17s/it]Device set to use cuda:0
 29%|██▉       | 7/24 [00:40<01:40,  5.90s/it]Device set to use cuda:0
 33%|███▎      | 8/24 [00:47<01:37,  6.07s/it]Device set to use cuda:0
 38%|███▊      | 9/24 [00:54<01:34,  6.32s/it]Device set to use cuda:0
 42%|████▏     | 10/24 [00:59<01:23,  5.94s/it]Device set to use cuda:0
 46%|████▌     | 11/24 [01:03<01:09,  5.32s/it]Device set to use cuda:0
 50%|█████     | 12/24 [01:08<01:05,  5.43s/it]Device set to use cuda:0
 54%|█████▍    | 13/24 [01:15<01:04,  5.85s/it]Device set to use cuda:0
 58%|█████▊    | 14/24 [01:21<00:58,  5.90s/it]Device set to use cuda:0
 62%|██████▎   | 15/24 [01:27<00:52,  5.83s/it]Device set to use cuda:0
 67%|██████▋   | 16/24 [01:35<00:52,  6.62s/it]Device set to use cuda:0
 71%|███████   | 17/24 [01:41<00:44,  6.40s/it]Device set to use cuda:0
 75%|███████▌  | 18/24 [01:48<00:38,  6.49s/it]Device set to use cuda:0
 79%|███████▉  | 19/24 [01:53<00:30,  6.01s/it]Device set to use cuda:0
 83%|████████▎ | 20/24 [01:59<00:24,  6.02s/it]Device set to use cuda:0
 88%|████████▊ | 21/24 [02:04<00:17,  5.89s/it]Device set to use cuda:0
 92%|█████████▏| 22/24 [02:10<00:11,  5.86s/it]Device set to use cuda:0
 96%|█████████▌| 23/24 [02:17<00:06,  6.05s/it]Device set to use cuda:0
100%|██████████| 24/24 [02:23<00:00,  5.96s/it]

In [10]:
df_results

   narrative                                             result
0        CH1  Response: This narrative, presented in a serie...
1        CH2  Response:\n\nThis narrative, titled "China is ...
2        CH3  \nResponse:\n\nThis narrative, "China has an e...
3        CH4  Response:\n\nThis narrative explores the persp...
4        CH5  \nResponse:\n\nThis narrative, titled "The gov...
5        CH6  Response:\n\nThis narrative offers an intrigui...
6        EU1  \nResponse: This narrative, titled "The Europe...
7        EU2  Response:\n\nIn this narrative, the European U...
8        EU3  Description: This narrative encapsulates the a...
9        EU4  response: This narrative explores the European...
10       EU5  Description: This narrative explores the Europ...
11       EU6  Response: This narrative explores the European...
12       RU1  Description: This narrative reflects a strongl...
13       RU2  Response: This narrative explores Russia's dis...
14       RU3  Description: This narrative, titled "Russia is...
15       RU4  Explanation:\n\nThe narrative titled "Russian ...
16       RU5  Response: \n\nThis narrative, titled "Russia i...
17       RU6  \nResponse: This narrative explores the multif...
18       US1  Response:\n\nThis narrative explores the endur...
19       US2  Response: This narrative reflects on the Unite...
20       US3  \nResponse: In this narrative, the United Stat...
21       US4  Response:\n\nThis narrative, titled "The US is...
22       US5  Description: This narrative explores the Unite...
23       US6  Response: This narrative, titled "The US is at...

In [11]:
name=f'z_s_{model_name}_only_title'
df_results.to_pickle(f'/data/jfraile/Programs/Narratives_Identification/narratives_descriptions/zero_shot_description/{name}.pkl')
df_results.to_json(f'/data/jfraile/Programs/Narratives_Identification/narratives_descriptions/zero_shot_description/{name}.json', orient='records', indent=2, force_ascii=False)

# Dipromats improved Description from title and Description

In [12]:
def get_prompt(country_id, title, description):
    if country_id=='USA':
        country='United States of America'
    elif country_id=='EU':
        country='European Union'
    else:
        country=country_id

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title and a paragraph with a description of a narrative about {country}. You also have to take into account the social, political and cultural context because the tweets were written throughout the year 2020. Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the narrative. Your description will have to help improve the identification of narratives in tweets.


Narrative title: {title} 
Description: {description}

Task: Generate a description of the narrative. 
    """
    return user_prompt

In [13]:
df_results=pd.DataFrame(columns=['narrative', 'result'])
for i in tqdm(range(len(narratives))):
    nar=narratives.iloc[i]
    country=nar['country']
    title=nar['title']
    n=nar['n_id'][-1]
    description=nar['description']
    dft=df[(df['country'] == country) & (df[f'N{n}'] != 'no')]
    examples=dft['text'].values
    prompt=get_prompt(country, title, description)
    result=interact_with_model(prompt)
    new_row = pd.DataFrame({'narrative': [nar['n_id']], 'result': [result]})
    df_results = pd.concat([df_results, new_row], ignore_index=True)

  0%|          | 0/24 [00:00<?, ?it/s]Device set to use cuda:0
  4%|▍         | 1/24 [00:07<02:50,  7.42s/it]Device set to use cuda:0
  8%|▊         | 2/24 [00:12<02:14,  6.12s/it]Device set to use cuda:0
 12%|█▎        | 3/24 [00:21<02:33,  7.30s/it]Device set to use cuda:0
 17%|█▋        | 4/24 [00:28<02:23,  7.17s/it]Device set to use cuda:0
 21%|██        | 5/24 [00:35<02:19,  7.34s/it]Device set to use cuda:0
 25%|██▌       | 6/24 [00:40<01:58,  6.56s/it]Device set to use cuda:0
 29%|██▉       | 7/24 [00:45<01:41,  5.95s/it]Device set to use cuda:0
 33%|███▎      | 8/24 [00:49<01:25,  5.35s/it]Device set to use cuda:0
 38%|███▊      | 9/24 [00:58<01:34,  6.33s/it]Device set to use cuda:0
 42%|████▏     | 10/24 [01:06<01:35,  6.81s/it]Device set to use cuda:0
 46%|████▌     | 11/24 [01:11<01:21,  6.27s/it]Device set to use cuda:0
 50%|█████     | 12/24 [01:23<01:36,  8.05s/it]Device set to use cuda:0
 54%|█████▍    | 13/24 [01:34<01:38,  8.96s/it]Device set to use cuda:0
 58%|█████▊    | 14/24 [01:39<01:17,  7.74s/it]Device set to use cuda:0
 62%|██████▎   | 15/24 [01:44<01:02,  6.98s/it]Device set to use cuda:0
 67%|██████▋   | 16/24 [01:48<00:48,  6.01s/it]Device set to use cuda:0
 71%|███████   | 17/24 [02:00<00:55,  7.97s/it]Device set to use cuda:0
 75%|███████▌  | 18/24 [02:05<00:41,  6.84s/it]Device set to use cuda:0
 79%|███████▉  | 19/24 [02:12<00:35,  7.12s/it]Device set to use cuda:0
 83%|████████▎ | 20/24 [02:19<00:28,  7.09s/it]Device set to use cuda:0
 88%|████████▊ | 21/24 [02:24<00:18,  6.32s/it]Device set to use cuda:0
 92%|█████████▏| 22/24 [02:30<00:12,  6.25s/it]Device set to use cuda:0
 96%|█████████▌| 23/24 [02:36<00:06,  6.25s/it]Device set to use cuda:0
100%|██████████| 24/24 [02:43<00:00,  6.82s/it]

In [14]:
df_results

   narrative                                             result
0        CH1  \nImproved Description: During the tumultuous ...
1        CH2  \n[Response]\n\nThis narrative portrays China ...
2        CH3  \nThe narrative "China has an epic history," u...
3        CH4  \n responds: \n\nThroughout 2020, a series of ...
4        CH5  \nResponse: This narrative, emerging in the co...
5        CH6  Responding:\n\nThis narrative unfolds as a vib...
6        EU1  \nResponse: This narrative presents a compelli...
7        EU2  \nResponse: In 2020, the European Union's stre...
8        EU3  \nThe tweet narrative advocates for the Europe...
9        EU4  \nThe European Union, in its dynamic and trans...
10       EU5  \nResponse:\n\nIn the dynamic landscape of 202...
11       EU6  \nThis narrative focuses on the pivotal role o...
12       RU1  \nThe narrative revolves around a stark contra...
13       RU2  \nResponse: This narrative explores Russia's s...
14       RU3  \nAssistant:\n\nIn 2020, a series of tweets un...
15       RU4  \nThe narrative celebrates Russia's rich and m...
16       RU5   responds:\n\nIn 2020, amidst a tumultuous glo...
17       RU6  Response: This narrative, spanning the year 20...
18       US1  \nThe narrative, titled "The US has an honorab...
19       US2  \nReply:\n\nThroughout 2020, this narrative ce...
20       US3  \nResponse:\n\nThis narrative centers on the p...
21       US4  \nRESPONSE:\n\nThis narrative illuminates the ...
22       US5  Response: Throughout 2020, a series of tweets ...
23       US6  \nAssistant:\n\nThe narrative titled "The US i...

In [15]:
name=f'z_s_{model_name}_description'
df_results.to_pickle(f'/data/jfraile/Programs/Narratives_Identification/narratives_descriptions/zero_shot_description/{name}.pkl')
df_results.to_json(f'/data/jfraile/Programs/Narratives_Identification/narratives_descriptions/zero_shot_description/{name}.json', orient='records', indent=2, force_ascii=False)

# Dipromats completed Description

In [16]:
def get_prompt(country_id, title, description):
    if country_id=='USA':
        country='United States of America'
    elif country_id=='EU':
        country='European Union'
    else:
        country=country_id

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive a paragraph with a description of a narrative about {country}. 
You also have to take into account the social, political and cultural context because the tweets were written throughout the year 2020. 
Your mission will be to rewrite the paragraph to improve the readability and interpretation of that text. Your description will have to help improve the identification of narratives in tweets. 
Write the characteristics that the model must have in terms of the social, political and economic context, the main actors involved in the narrative, what emotions the message seeks to provoke and the conclusions it wants the reader to reach, and the main textual characteristics. 


Narrative title: {title} 
Description: {description}

    """
    return user_prompt

In [17]:
df_results=pd.DataFrame(columns=['narrative', 'result'])
for i in tqdm(range(len(narratives))):
    nar=narratives.iloc[i]
    country=nar['country']
    title=nar['title']
    n=nar['n_id'][-1]
    description=nar['description']
    dft=df[(df['country'] == country) & (df[f'N{n}'] != 'no')]
    examples=dft['text'].values
    prompt=get_prompt(country, title, description)
    result=interact_with_model(prompt)
    new_row = pd.DataFrame({'narrative': [nar['n_id']], 'result': [result]})
    df_results = pd.concat([df_results, new_row], ignore_index=True)

  0%|          | 0/24 [00:00<?, ?it/s]Device set to use cuda:0
  4%|▍         | 1/24 [00:13<05:01, 13.11s/it]Device set to use cuda:0
  8%|▊         | 2/24 [00:26<04:48, 13.11s/it]Device set to use cuda:0
 12%|█▎        | 3/24 [00:37<04:20, 12.39s/it]Device set to use cuda:0
 17%|█▋        | 4/24 [00:50<04:11, 12.58s/it]Device set to use cuda:0
 21%|██        | 5/24 [01:03<04:01, 12.69s/it]Device set to use cuda:0
 25%|██▌       | 6/24 [01:14<03:37, 12.06s/it]Device set to use cuda:0
 29%|██▉       | 7/24 [01:27<03:29, 12.35s/it]Device set to use cuda:0
 33%|███▎      | 8/24 [01:40<03:20, 12.54s/it]Device set to use cuda:0
 38%|███▊      | 9/24 [01:53<03:09, 12.62s/it]Device set to use cuda:0
 42%|████▏     | 10/24 [02:05<02:54, 12.48s/it]Device set to use cuda:0
 46%|████▌     | 11/24 [02:18<02:44, 12.62s/it]Device set to use cuda:0
 50%|█████     | 12/24 [02:30<02:30, 12.56s/it]Device set to use cuda:0
 54%|█████▍    | 13/24 [02:42<02:16, 12.40s/it]Device set to use cuda:0
 58%|█████▊    | 14/24 [02:55<02:05, 12.53s/it]Device set to use cuda:0
 62%|██████▎   | 15/24 [03:07<01:51, 12.37s/it]Device set to use cuda:0
 67%|██████▋   | 16/24 [03:20<01:40, 12.51s/it]Device set to use cuda:0
 71%|███████   | 17/24 [03:33<01:28, 12.61s/it]Device set to use cuda:0
 75%|███████▌  | 18/24 [03:46<01:16, 12.72s/it]Device set to use cuda:0
 79%|███████▉  | 19/24 [03:59<01:03, 12.79s/it]Device set to use cuda:0
 83%|████████▎ | 20/24 [04:12<00:51, 12.88s/it]Device set to use cuda:0
 88%|████████▊ | 21/24 [04:25<00:38, 12.88s/it]Device set to use cuda:0
 92%|█████████▏| 22/24 [04:38<00:25, 12.93s/it]Device set to use cuda:0
 96%|█████████▌| 23/24 [04:50<00:12, 12.92s/it]Device set to use cuda:0
100%|██████████| 24/24 [05:03<00:00, 12.67s/it]

In [18]:
df_results

   narrative                                             result
0        CH1  [Answer]\n\n# Improved Prompt:\n\nTitle: Analy...
1        CH2  [Answer]\n\nNarrative Title: China's Global Le...
2        CH3  [Response]\n\nTitle: China's Unyielding Histor...
3        CH4  [Response]\n\nNarrative Title: Celebrating Chi...
4        CH5  [Response]\n\nNarrative Title: "China's Centra...
5        CH6  [Response]:\n\nTitle: "Exploring the Rich Tape...
6        EU1  [Response]\n\nNarrative Title: Triumphs of the...
7        EU2  [Revised Prompt]\n\nYour task is to refine the...
8        EU3  [Response]\n\nTitle: "Empowering European Citi...
9        EU4  Response:\n\nNarrative Title: The EU Leads the...
10       EU5  \n[Response]\n\nNarrative Title: The European ...
11       EU6  [Response]:\n\nTitle: "EU's Global Impact: A B...
12       RU1  [Answer]\n\nNarrative Title: Western Critique ...
13       RU2  Revised Paragraph:\n\nThroughout 2020, amidst ...
14       RU3  [Response]\n\nRevised Prompt:\n\n"Craft a comp...
15       RU4  [Revised Prompt]\n\nRevised Prompt:\n\nCraft a...
16       RU5  [Answer]\n\nTitle: #RussiaRising: A Triumph of...
17       RU6  [Response]\n\nNarrative Title: Russia's Rich C...
18       US1  1. Social context: The description should ackn...
19       US2  [/Assistant]\n\nRevised Prompt:\n\nTitle: "Cel...
20       US3  [Response]\n\nNarrative Title: "US Faces Hosti...
21       US4  [Reply]\n\nNarrative Title: "United States: A ...
22       US5  [Answer]\n\n# Narrative Title: United States S...
23       US6  [Response]:\n\nRevised Prompt:\n\nTitle: Unvei...

In [19]:
name=f'z_s_{model_name}_description_complete'
df_results.to_pickle(f'/data/jfraile/Programs/Narratives_Identification/narratives_descriptions/zero_shot_description/{name}.pkl')
df_results.to_json(f'/data/jfraile/Programs/Narratives_Identification/narratives_descriptions/zero_shot_description/{name}.json', orient='records', indent=2, force_ascii=False)