In [1]:
import pandas as pd
from tqdm import tqdm
from openai import OpenAI
import time

### Chat Model

In [ ]:
# Configura tu clave de API
client = OpenAI(
    api_key=""
)

gpt_model='gpt-4o-mini'
# gpt_model="gpt-3.5-turbo"
def interact_with_model(prompt, model=gpt_model, max_tokens=2000):

    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=max_tokens
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"API Error : {e}"

In [4]:
df_titles_desc=pd.read_json('/home/jfraile/Programs/datasets/SemEval_2025_T10_S2/titles_and_descriptions.json')
ids_with_title_desc=df_titles_desc.id.values

allowed_subnarratives=['URW1.1', 'URW1.2', 'URW1.OTH', 'URW2.1', 'URW2.2', 'URW2.3', 'URW2.4', 'URW2.5', 'URW2.6', 'URW2.7', 'URW2.8', 'URW2.OTH', 'URW3.1', 'URW3.2', 'URW3.3', 'URW3.OTH', 'URW4.1', 'URW4.2', 'URW4.3', 'URW4.4', 'URW4.5', 'URW4.OTH', 'URW5.1', 'URW5.2', 'URW5.3', 'URW5.OTH', 'URW6.1', 'URW6.2', 'URW6.3', 'URW6.OTH', 'URW7.1', 'URW7.2', 'URW7.3', 'URW7.4', 'URW7.5', 'URW7.6', 'URW7.OTH', 'URW8.1', 'URW8.2', 'URW8.OTH', 'URW9.1', 'URW9.2', 'URW9.OTH', 'URW10.1', 'URW10.2', 'URW10.3', 'URW10.4', 'URW10.OTH', 'URW11.OTH', 'CC1.1', 'CC1.2', 'CC1.3', 'CC1.OTH', 'CC2.1', 'CC2.2', 'CC2.3', 'CC2.4', 'CC2.OTH', 'CC3.1', 'CC3.2', 'CC3.OTH', 'CC4.1', 'CC4.2', 'CC4.3', 'CC4.4', 'CC4.5', 'CC4.6', 'CC4.7', 'CC4.8', 'CC4.OTH', 'CC5.1', 'CC5.2', 'CC5.3', 'CC5.4', 'CC5.OTH', 'CC6.1', 'CC6.2', 'CC6.3', 'CC6.OTH', 'CC7.1', 'CC7.2', 'CC7.3', 'CC7.4', 'CC7.OTH', 'CC8.1', 'CC8.2', 'CC8.OTH', 'CC9.1', 'CC9.2', 'CC9.3', 'CC9.4', 'CC9.OTH', 'CC10.1', 'CC10.2', 'CC10.OTH', 'OTH.OTH']

allowed_narratives=[f'URW{i}.' for i in range(1,12)] + [f'CC{i}.' for i in range(1,11)]

# Description from titles

In [15]:
def get_prompt_subnarr(narr, title_subnarr):

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title of a subnarrative about the narrative "{narr}". Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the subnarrative. Your description will have to help improve the identification of subnarratives in news.

Subnarrative title: {title_subnarr} 

Task: Generate a description of the subnarrative. 
    """
    return user_prompt

def get_prompt_narr(narr):

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title of a narrative. Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the narrative. Your description will have to help improve the identification of narratives in news.

Narrative title: {narr} 

Task: Generate a description of the narrative. 
    """
    return user_prompt

In [ ]:
name='gpt_z_s_desc_only_title'
try:
    df_results=pd.read_json(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}.json')
    df_results=df_results[df_results['description'].apply(lambda x: 'API Error not in x)]
except:    
    df_results=pd.DataFrame(columns=['id', 'description'])

for subnarr in tqdm(allowed_subnarratives):
    if 'OTH' in subnarr:
        continue
    try:
        t=df_results[df_results['id']==subnarr]['description'].iloc[0]
    except:
        t='API Error
    if 'API Error in t:
        narr=subnarr.split('.')[0]+'.'
        narr_title=df_titles_desc[df_titles_desc['id']==narr]['title'].iloc[0]
        narr_desc=df_titles_desc[df_titles_desc['id']==narr]['description'].iloc[0]
        subnarr_title=df_titles_desc[df_titles_desc['id']==subnarr]['title'].iloc[0]
        subnarr_desc=df_titles_desc[df_titles_desc['id']==subnarr]['description'].iloc[0]
        prompt=get_prompt_subnarr(narr_title, subnarr_title)
        result=interact_with_model(prompt)
        new_row = pd.DataFrame([{'id':subnarr, 'description': result}])
        df_results = pd.concat([df_results, new_row], ignore_index=True)

for narr in tqdm(allowed_narratives):
    try:
        t=df_results[df_results['id']==narr]['description'].iloc[0]
    except:
        t='API Error
    if 'API Error in t:
        narr_title=df_titles_desc[df_titles_desc['id']==narr]['title'].iloc[0]
        narr_desc=df_titles_desc[df_titles_desc['id']==narr]['description'].iloc[0]

        prompt=get_prompt_narr(narr_title)
        result=interact_with_model(prompt)
        new_row = pd.DataFrame([{'id':narr, 'description': result}])
        df_results = pd.concat([df_results, new_row], ignore_index=True)

100%|██████████| 96/96 [00:00<00:00, 4916.76it/s]
  0%|          | 0/21 [00:00<?, ?it/s]

100%|██████████| 21/21 [06:00<00:00, 17.17s/it]

In [18]:
df_results

        id                                        description
0   URW1.1  The subnarrative titled "Ukraine is the aggres...
1   URW1.2  The West are the Aggressors**\n\nIn the contex...
2   URW2.1  The subnarrative "Rewriting Ukraine’s History"...
3   URW2.2  The subnarrative titled "Discrediting Ukrainia...
4   URW2.3  The subnarrative "Discrediting Ukrainian Milit...
..     ...                                                ...
90    CC6.  The narrative titled "Criticism of Climate Mov...
91    CC7.  The narrative titled "Controversy about Green ...
92    CC8.  In a world where shadows often obscure the tru...
93    CC9.  In the narrative titled "Amplifying Climate Fe...
94   CC10.  The narrative titled "Green policies are geopo...

[95 rows x 2 columns]

In [20]:
df_results.to_pickle(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}_v2.pkl')
df_results.to_json(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}_v2.json', orient='records', indent=2, force_ascii=False)

# Improved Description from title and Description

In [21]:
def get_prompt_subnarr(narr, title_subnarr, desc_subnarr):

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title of a subnarrative about the narrative "{narr}". Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the subnarrative. Your description will have to help improve the identification of subnarratives in news.

Subnarrative title: {title_subnarr} 
Description: {desc_subnarr}

Task: Generate a description of the subnarrative. 
    """
    return user_prompt

def get_prompt_narr(narr, desc_narr):

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title of a narrative. Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the narrative. Your description will have to help improve the identification of narratives in news.

Narrative title: {narr} 
Description: {desc_narr}

Task: Generate a description of the narrative. 
    """
    return user_prompt

In [ ]:
name='gpt_z_s_desc_title_description'

try:
    df_results=pd.read_json(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}.json')
    df_results=df_results[df_results['description'].apply(lambda x: 'API Error not in x)]
except:    
    df_results=pd.DataFrame(columns=['id', 'description'])

for subnarr in tqdm(allowed_subnarratives):
    if 'OTH' in subnarr:
        continue
    try:
        t=df_results[df_results['id']==subnarr]['description'].iloc[0]
    except:
        t='API Error
    if 'API Error in t:
        narr=subnarr.split('.')[0]+'.'
        narr_title=df_titles_desc[df_titles_desc['id']==narr]['title'].iloc[0]
        narr_desc=df_titles_desc[df_titles_desc['id']==narr]['description'].iloc[0]
        subnarr_title=df_titles_desc[df_titles_desc['id']==subnarr]['title'].iloc[0]
        subnarr_desc=df_titles_desc[df_titles_desc['id']==subnarr]['description'].iloc[0]
        prompt=get_prompt_subnarr(narr_title, subnarr_title, subnarr_desc)
        result=interact_with_model(prompt)
        print(result)
        new_row = pd.DataFrame([{'id':subnarr, 'description': result}])
        df_results = pd.concat([df_results, new_row], ignore_index=True)

for narr in tqdm(allowed_narratives):
    try:
        t=df_results[df_results['id']==narr]['description'].iloc[0]
    except:
        t='API Error
    if 'API Error in t:
        narr_title=df_titles_desc[df_titles_desc['id']==narr]['title'].iloc[0]
        narr_desc=df_titles_desc[df_titles_desc['id']==narr]['description'].iloc[0]

        prompt=get_prompt_narr(narr_title, narr_desc)
        result=interact_with_model(prompt)
        print(result)
        new_row = pd.DataFrame([{'id':narr, 'description': result}])
        df_results = pd.concat([df_results, new_row], ignore_index=True)

100%|██████████| 96/96 [00:00<00:00, 2548.41it/s]

  5%|▍         | 1/21 [00:03<01:04,  3.21s/it]

This narrative explores the tendency to deflect responsibility for the ongoing war in Ukraine by attributing blame to external parties rather than acknowledging the actions of the Russian invader. It highlights various statements and sentiments that either explicitly or implicitly suggest that forces such as Western governments, NATO, or even Ukraine itself are culpable for the conflict and its repercussions. Examples include claims suggesting that economic turmoil is a direct result of sanctions imposed by Western nations, or that Ukraine has provoked Russia's aggression through its own actions. By analyzing these narratives, one can gain insight into the complex dynamics of blame, propaganda, and the framing of accountability in the context of international conflict, helping to clarify the motivations behind certain statements and the broader implications for public perception and discourse surrounding the war.

 10%|▉         | 2/21 [00:06<00:59,  3.16s/it]

The narrative titled "Discrediting Ukraine" encompasses a range of statements and claims that serve to undermine the legitimacy and credibility of Ukraine as a sovereign nation and its people. This narrative often manifests through assertions that question the integrity and effectiveness of Ukrainian institutions, such as the government or military, suggesting that they are rife with corruption, incompetence, or moral failings. It may also involve broader cultural attacks, casting doubt on the existence or authenticity of a cohesive Ukrainian identity. For instance, accusations of war crimes against Ukrainian forces or claims of widespread societal dysfunction reflect this narrative's aim to delegitimize Ukraine on both a national and international stage. When analyzing stories or commentary, look for language that directly challenges these aspects of Ukrainian society, as they indicate a concerted effort to erode support for Ukraine and its people amid ongoing geopolitical tensions.

 14%|█▍        | 3/21 [00:10<01:05,  3.65s/it]

In this narrative, Russia is framed as a beleaguered nation facing unjust external pressures and hostilities, often invoking themes of victimization and sympathy. The discourse emphasizes the perception that Russia's actions are defensive rather than aggressive, suggesting that the country is being unfairly demonized by Western powers. Statements such as "Russia is being unfairly sanctioned" and "The West is ganging up on Russia without justification" are integral to this narrative, reflecting a belief that Russia's response to perceived threats is both natural and justified. The language typically appeals to national pride, asserting that Russia is merely protecting its interests, sovereignty, and honor, comparable to actions any nation would take under similar circumstances. This framing seeks to garner empathy for Russia, painting it as a nation struggling against unwarranted aggression and striving to defend its dignity on the global stage.

 19%|█▉        | 4/21 [00:33<03:11, 11.25s/it]

The narrative titled "Praise of Russia" encompasses a range of statements and sentiments that underscore a favorable view of the country’s actions, policies, and overall character. In this narrative, expressions of admiration and support are prominent, reflecting a positive evaluation of Russian endeavors on both domestic and international fronts. This includes explicit endorsements such as "Russia is leading the way in international diplomacy," which highlights the country’s diplomatic efforts, as well as more nuanced commendations like "The Russian economy is resilient and strong," showcasing its financial stability. Additionally, there are glorifying mentions of Russia’s military capabilities, reflecting a sense of pride in its weapon systems and defense strategy. Overall, the narrative seeks to identify and analyze both overt and subtle forms of praise for Russia, contributing to a broader understanding of its portrayal in various contexts.

 24%|██▍       | 5/21 [00:56<04:07, 15.50s/it]

The narrative titled "Overpraising the West" explores the tendency of politicians, media outlets, and influencers to excessively celebrate and glorify the achievements and ethical standings of Western nations, often at the expense of a balanced perspective. This phenomenon is particularly evident in discussions surrounding international relations and military interventions, where Western powers are portrayed as unequivocally benevolent and righteous. The narrative critiques this one-dimensional portrayal, highlighting the risks of such overzealous commendation, which can lead to a lack of critical analysis regarding Western policies, actions, and their implications on global dynamics. By examining the implications of this bias, the narrative invites readers to consider the importance of a nuanced understanding of international affairs that acknowledges both the accomplishments and shortcomings of Western countries.

 29%|██▊       | 6/21 [01:19<04:31, 18.11s/it]

In the complex landscape of international relations, "Speculating War Outcomes" encapsulates the critical discourse surrounding the anticipated results of armed conflicts. This narrative delves into analyses and predictions regarding how wars might unfold, including potential victories, losses, political shifts, and humanitarian repercussions. It reflects the perspectives of analysts, commentators, and leaders who assess various factors such as military strategy, geopolitical alliances, and historical contexts to gauge possible scenarios. By exploring both optimistic and pessimistic forecasts, this narrative highlights the uncertainty and multifaceted nature of war, offering insight into its far-reaching implications on nations and global stability. Understanding this narrative is essential for comprehending the broader implications of military engagement and the strategic decisions that shape contemporary conflicts.

 33%|███▎      | 7/21 [01:42<04:35, 19.69s/it]

In this narrative, the focus is on statements and sentiments that seek to undermine the credibility and effectiveness of Western countries and their diplomatic initiatives. It encompasses critiques that highlight perceived failures, biases, or inconsistencies in Western foreign policy and actions. The language often conveys a sense of distrust or disillusionment, suggesting that Western leaders are either inept, hypocritical, or acting with malicious intent in international affairs. Effective examples might include assertive claims such as "The West often prioritizes its interests over global justice" or "Western nations' attempts at diplomacy are mere facade concealing deeper geopolitical ambitions." Observers should be attuned to language that strongly expresses dissatisfaction with the role that Western powers play in global governance, emphasizing a belief that their efforts often exacerbate rather than alleviate conflicts.

 38%|███▊      | 8/21 [01:45<03:05, 14.24s/it]

The narrative titled "Negative Consequences for the West" revolves around statements, analyses, and projections that underscore the potential adverse effects faced by Western countries in the context of geopolitical events, economic decisions, and international relations. This narrative encompasses a wide range of discussions, including the repercussions of sanctions, economic policies, and diplomatic strategies that may harm Western interests both now and in the future. For instance, insights might suggest that aggressive sanctions imposed on nations like Russia could ultimately lead to detrimental economic repercussions for European countries. Similarly, warnings about looming economic downturns and political instability within the West illustrate the urgent need for a reassessment of current strategies. Readers should look for critical assessments and forecasts that paint a cautionary picture of the West's trajectory in relation to global events.

 43%|████▎     | 9/21 [02:08<03:25, 17.11s/it]

The narrative titled "Distrust towards Media" encompasses a growing sentiment where individuals and communities express skepticism and apprehension regarding the accuracy and trustworthiness of media outlets. It highlights language and phrases that cast doubt on the integrity of journalism, suggesting that media organizations may be prone to bias, misinformation, or deliberate manipulation. Key themes to explore within this narrative include accusations of propaganda dissemination, particularly with regards to geopolitical issues, as well as the overall perception that news sources are not presenting an unbiased account of events. Examples to note include statements like "Western media is spreading propaganda" or "You can’t trust what the news says about Russia," which reflect a critical view toward the motives and reliability of mainstream information providers. Analyzing such expressions can provide insights into the factors driving public skepticism and the implications for media consumption in today’s information landscape.

 48%|████▊     | 10/21 [02:32<03:29, 19.06s/it]

The narrative titled "Amplifying War-Related Fears" delves into the pervasive rhetoric and language that heightens public anxiety regarding global conflicts. It meticulously examines the statements and assertions that are crafted to instill a sense of impending doom or unease about military escalations and their catastrophic implications. This narrative highlights specific phrases that starkly convey the urgency and severity of potential threats, such as remarks about the risk of a World War III sparked by geopolitical tensions, ominous predictions about the spread of war to Western nations, and the alarming notion that nuclear conflict might be just around the corner. By analyzing both overt and subtle expressions of fear, this narrative calls for scrutiny of how language can be wielded to shape perceptions and reactions to international relations, thereby influencing public sentiment and policy discourse around war and security issues.

 57%|█████▋    | 12/21 [02:54<02:19, 15.45s/it]

The narrative titled "Criticism of Climate Policies" encompasses a range of statements and viewpoints that challenge the current strategies implemented to address climate change. This narrative highlights the skepticism surrounding the effectiveness of various climate initiatives, debates their potential economic consequences, and scrutinizes the motives driving these policies. For instance, critics may argue that the decision to transition to electric vehicles is misguided or not sufficiently impactful in the battle against climate change. By examining these criticisms, one can gain insight into the concerns raised by different stakeholders—including economists, environmental activists, and the general public—regarding whether current policies adequately address climate issues or whether alternative approaches should be considered. This narrative serves as a lens through which to understand the complexities and controversies surrounding climate action, revealing the ongoing discourse about the best paths forward for sustainability and economic viability.

 62%|██████▏   | 13/21 [03:17<02:17, 17.24s/it]

This narrative explores the growing skepticism and critique directed towards governmental institutions, scientific organizations, and authoritative figures regarding their handling of climate change issues. It highlights voices that question the efficacy, transparency, and motivations of these bodies in addressing one of the most pressing global challenges of our time. With an emphasis on both individual and collective concerns, the narrative uncovers how these criticisms reflect broader societal frustrations and calls for accountability, demanding more robust actions and policies to combat climate change. By dissecting statements from activists, policymakers, and the public, this narrative emphasizes how trust in these institutions is being tested and the implications this has for climate action and public discourse.

 67%|██████▋   | 14/21 [03:39<02:10, 18.62s/it]

Description: This narrative explores the concept that climate change, often viewed solely through a negative lens, can have certain beneficial effects in specific contexts. It presents arguments highlighting potential advantages such as increased agricultural yields in certain regions due to longer growing seasons, the melting of polar ice opening new shipping routes, and the possibility of richer biodiversity in newly habitable areas. By analyzing various scientific studies and expert opinions, this narrative aims to provide a balanced perspective on the multifaceted impacts of climate change, emphasizing that, while acknowledging the severe risks, it is crucial to also consider scenarios where the changes may lead to unexpected positive outcomes.

 71%|███████▏  | 15/21 [04:02<01:58, 19.73s/it]

The narrative titled "Downplaying Climate Change" revolves around the communication strategies and rhetoric used by various individuals and organizations to diminish or dismiss the urgency and severity of climate change issues. This includes a range of statements that trivialize the consequences of rising global temperatures, extreme weather events, and ecological degradation, often framing them as exaggerated concerns or politically motivated claims. This narrative can be found in political discourse, media coverage, and public debates, where it serves to create doubt about scientific consensus and hinder collective action. By examining the language and framing involved in such downplaying, we can better understand the broader implications for environmental policy and public awareness regarding climate action.

 76%|███████▌  | 16/21 [04:04<01:14, 14.83s/it]

In the narrative titled "Questioning the Measurements and Science," the focus centers on the emergence of skepticism regarding established scientific methods and data relevant to climate change. This narrative delves into the various statements and arguments that challenge the validity of scientific measurements and the consensus among researchers on climate-related issues. It highlights the concerns of individuals and groups who question the accuracy of data collection, the interpretation of results, and the reliability of climate models. By examining these doubts, the narrative underscores a growing discourse about the rigor of scientific inquiry and the debates surrounding climate science, ultimately inviting readers to consider the implications of such skepticism on public policy, environmental awareness, and global action against climate change.

 81%|████████  | 17/21 [04:28<01:08, 17.25s/it]

Description: This narrative encapsulates a wave of skepticism directed towards the climate movement, articulating concerns over its strategies, motivations, and the potential consequences of its actions. Critics argue that the movement tends to prioritize alarmist rhetoric over measured discourse, leading to a perception of over-dramatization regarding climate change risks. Similar assertions suggest that detractors are often marginalized within the scientific community, which some believe tilts towards a singular narrative of impending catastrophe. This critique not only questions the scientific validity of climate claims but also examines the broader implications of a potentially dogmatic approach to environmental activism. By framing these discussions, the narrative invites readers to consider the complexities and contradictions that exist within the climate debate, ultimately fostering a dialogue around the legitimacy of dissenting voices in a cause often viewed as universally necessary.

 86%|████████▌ | 18/21 [04:50<00:56, 18.80s/it]

In the ongoing debate surrounding green technologies, various stakeholders have voiced their doubts and concerns regarding the efficacy and practicality of these environmentally friendly solutions. This narrative highlights the opposition to renewable energy sources, electric vehicles, and sustainable practices, emphasizing potential drawbacks such as reliance on rare materials, the carbon footprint of manufacturing processes, and the economic implications of transitioning to greener options. Critics often argue that while the intentions behind these technologies are commendable, their implementation may lead to unintended negative consequences or insufficient results in combating climate change. This controversy underscores the complexity of achieving true sustainability in a world where technological advancements are not always straightforward answers to environmental challenges.

 90%|█████████ | 19/21 [05:13<00:39, 19.88s/it]

This narrative explores the notion that influential organizations or elites may be orchestrating covert schemes aimed at shaping the discourse and policies surrounding climate change. It delves into the idea that behind the public rhetoric of environmental sustainability and corporate responsibility, there may lie undisclosed motives and agendas that prioritize power and profit over genuine ecological concern. It raises questions about the transparency of actions taken by these powerful groups and the potential ramifications of their unseen influence on climate policies and initiatives. Through the lens of conspiracy theories or hidden machinations, the narrative invites readers to scrutinize the validity of public relations narratives and consider the potential consequences of unchecked authority in the global fight against climate change.

 95%|█████████▌| 20/21 [05:35<00:20, 20.70s/it]

Description: The narrative of "Amplifying Climate Fears" encapsulates the rhetoric and messaging strategies employed by various stakeholders—such as media, advocacy groups, and politicians—that highlight the urgent and potentially devastating impacts of climate change. This narrative often showcases vivid scenarios of environmental disasters, economic downturns, and humanitarian crises linked to rising global temperatures, extreme weather events, and loss of biodiversity. By focusing on alarming statistics and emotional testimonies, it seeks to draw attention to the gravity of the climate crisis, motivating public action and policy reform. However, it can also lead to heightened anxiety among the public, influencing perceptions and behaviors regarding climate action and adaptability. Understanding this narrative is crucial for analyzing how climate-related communication shapes societal responses to environmental issues.

100%|██████████| 21/21 [05:58<00:00, 17.06s/it]

Description: This narrative explores the assertion that environmental policies and initiatives, often touted as efforts to combat climate change and promote sustainability, may actually serve as strategic instruments for nations to enhance their geopolitical power and influence. It suggests that while these green policies are publicly presented as altruistic endeavors aimed at protecting the planet, underlying motivations may include gaining economic advantages, establishing dominance in emerging renewable energy markets, or manipulating international relations. Through an examination of various case studies and statements from global leaders, the narrative raises critical questions about the authenticity of environmental commitments and underscores the complex intersection between ecological stewardship and political maneuvering on the world stage.

In [23]:
df_results

        id                                        description
0   URW1.1  The subnarrative titled "Ukraine is the aggres...
1   URW1.2  This subnarrative frames the conflict as prima...
2   URW2.1  This subnarrative encompasses various assertio...
3   URW2.2  The subnarrative titled "Discrediting Ukrainia...
4   URW2.3  The subnarrative "Discrediting Ukrainian Milit...
..     ...                                                ...
90    CC6.  Description: This narrative encapsulates a wav...
91    CC7.  In the ongoing debate surrounding green techno...
92    CC8.  This narrative explores the notion that influe...
93    CC9.  Description: The narrative of "Amplifying Clim...
94   CC10.  Description: This narrative explores the asser...

[95 rows x 2 columns]

In [24]:
name='gpt_z_s_desc_title_description'
df_results.to_pickle(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}_v2.pkl')
df_results.to_json(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}_v2.json', orient='records', indent=2, force_ascii=False)

# Completed Description

In [5]:
def get_prompt_subnarr(narr, title_subnarr, desc_subnarr):

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title of a subnarrative about the narrative "{narr}". Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the subnarrative. Your description will have to help improve the identification of subnarratives in news.
Write the characteristics that the model must have in terms of the social, political and economic context, the main actors involved in the subnarrative, what emotions the message seeks to provoke and the conclusions it wants the reader to reach, and the main textual characteristics. 

Subnarrative title: {title_subnarr} 
Description: {desc_subnarr}

Task: Generate a description of the subnarrative. 
    """
    return user_prompt

def get_prompt_narr(narr, desc_narr):

    user_prompt = f"""
You are an expert at improving prompts for language models. You are going to receive the title of a narrative. Your mission will be to write a descriptive paragraph to improve the readability and interpretation of the narrative. Your description will have to help improve the identification of narratives in news.
Write the characteristics that the model must have in terms of the social, political and economic context, the main actors involved in the narrative, what emotions the message seeks to provoke and the conclusions it wants the reader to reach, and the main textual characteristics. 

Narrative title: {narr} 
Description: {desc_narr}

Task: Generate a description of the subnarrative. 
    """
    return user_prompt

In [ ]:
name='gpt_z_s_desc_title_description_complete'

try:
    df_results=pd.read_json(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}.json')
    df_results=df_results[df_results['description'].apply(lambda x: 'API Error not in x)]
except:    
    df_results=pd.DataFrame(columns=['id', 'description'])

for subnarr in tqdm(allowed_subnarratives):
    if 'OTH' in subnarr:
        continue
    try:
        t=df_results[df_results['id']==subnarr]['description'].iloc[0]
    except:
        t='API Error
    if 'API Error in t:
        narr=subnarr.split('.')[0]+'.'
        narr_title=df_titles_desc[df_titles_desc['id']==narr]['title'].iloc[0]
        narr_desc=df_titles_desc[df_titles_desc['id']==narr]['description'].iloc[0]
        subnarr_title=df_titles_desc[df_titles_desc['id']==subnarr]['title'].iloc[0]
        subnarr_desc=df_titles_desc[df_titles_desc['id']==subnarr]['description'].iloc[0]
        prompt=get_prompt_subnarr(narr_title, subnarr_title, subnarr_desc)
        result=interact_with_model(prompt)
        print(result)
        new_row = pd.DataFrame([{'id':subnarr, 'description': result}])
        df_results = pd.concat([df_results, new_row], ignore_index=True)

for narr in tqdm(allowed_narratives):
    try:
        t=df_results[df_results['id']==narr]['description'].iloc[0]
    except:
        t='API Error
    if 'API Error in t:
        narr_title=df_titles_desc[df_titles_desc['id']==narr]['title'].iloc[0]
        narr_desc=df_titles_desc[df_titles_desc['id']==narr]['description'].iloc[0]

        prompt=get_prompt_narr(narr_title, narr_desc)
        result=interact_with_model(prompt)
        print(result)
        new_row = pd.DataFrame([{'id':narr, 'description': result}])
        df_results = pd.concat([df_results, new_row], ignore_index=True)
        time.sleep(30)

100%|██████████| 96/96 [00:00<00:00, 4830.99it/s]

  0%|          | 0/21 [00:00<?, ?it/s]

**Description:**

The subnarrative titled "Overpraising the West" explores the phenomenon of hyperbolic adulation directed towards Western nations, particularly in the realms of international relations, human rights, and military intervention. This narrative is set against a backdrop of global social, political, and economic dynamics, where the actions and policies of Western countries are often depicted as exemplary or morally superior compared to those of non-Western nations. Key actors in this narrative include political leaders, media outlets, and academic institutions that perpetuate the image of Western superiority. The narrative seeks to provoke a sense of pride and a belief in the benefits of Western hegemony, while simultaneously fostering skepticism or resentment towards other global players. Readers are encouraged to critically evaluate the implications of such overpraising, considering how it can lead to biased perceptions and foster divisions in international relations. Textually, this narrative employs persuasive language, anecdotal evidence, and rhetorical flourishes that elevate Western achievements, often overshadowing counter-narratives that highlight the complexities and contributions of non-Western countries. It may also incorporate emotional appeals aimed at eliciting admiration and loyalty toward Western ideals, ultimately guiding readers toward a conclusion that underscores the need for a more nuanced understanding of global dynamics.

 24%|██▍       | 5/21 [00:34<01:49,  6.87s/it]

**Description of the Subnarrative: Speculating War Outcomes**

In the context of ongoing global tensions and military conflicts, the subnarrative "Speculating War Outcomes" delves into the multifaceted implications of warfare, encompassing social, political, and economic dimensions. The narrative often features a range of actors, including government officials, military analysts, and international organizations, who contribute their perspectives on likely scenarios. It captures the uncertainty and fear surrounding the potential escalation of conflict, evoking emotions such as anxiety, urgency, and powerlessness among the public and stakeholders. The discourse aims to provoke critical thinking about the ramifications of war, urging readers to consider not only the immediate fallout but also long-term geopolitical shifts and humanitarian crises. Main textual characteristics include speculative language, the use of statistics or historical precedents to reinforce arguments, and a balanced presentation of differing viewpoints to ensure a comprehensive understanding of the complex situation at hand. It often culminates in cautionary conclusions, emphasizing the need for diplomatic solutions and the risks of miscalculated assumptions in the context of war.

 29%|██▊       | 6/21 [01:08<03:12, 12.85s/it]

**Narrative Title: Discrediting the West, Diplomacy**

**Description:** This narrative explores the critical discourse surrounding Western nations and their diplomatic endeavors, particularly in the context of global politics and international relations. It reflects a socio-political climate marked by skepticism towards the effectiveness and motives of Western governments and international organizations. The main actors involved often include political leaders, diplomats, and institutions like the United Nations, portrayed through a lens of blame for international conflicts and crises. The language employed is charged with emotion, aiming to evoke feelings of distrust, frustration, and indignation among the audience. Statements that characterize Western policies as hypocritical or detrimental to global stability serve to galvanize dissent against perceived imperialistic or self-serving agendas. The narrative seeks to lead the reader to conclude that Western diplomacy is fundamentally flawed and ineffective in addressing global issues, arguing for alternative approaches or a reassessment of the balance of power in international relations. Textually, the narrative employs rhetorical strategies like hyperbole, anecdotal evidence, and charged adjectives to strengthen its argument, often utilizing a provocative tone that challenges the status quo and calls for a reevaluation of Western influence on world affairs.

 33%|███▎      | 7/21 [01:41<04:10, 17.88s/it]

**Description of the Subnarrative: Negative Consequences for the West**

This subnarrative explores the potential repercussions that Western nations might face due to geopolitical actions, economic decisions, and social dynamics. It typically involves a critical examination of Western policies, particularly those targeting rival states like Russia or China. The main actors in this narrative include government leaders, economists, international relations experts, and media figures who express concerns over the feasibility of current Western strategies. Emotionally, the narrative aims to evoke a sense of urgency and anxiety, pushing the reader to question the sustainability of the West's dominant position in global affairs. Key conclusions might suggest that continued sanctions or isolationist policies could inadvertently harm the West's own economic stability, leading to a decline in global influence and domestic unrest. Textually, the narrative often employs predictive language, cautionary tones, and factual references to economic indicators, making use of statistics and expert opinions to reinforce claims. The structure frequently includes contrasting perspectives, highlighting the threats posed by external actions juxtaposed with the West's vulnerabilities, ultimately underscoring the fragility of its current geopolitical standing.

 38%|███▊      | 8/21 [02:15<04:45, 21.93s/it]

**Description:**

The narrative titled "Amplifying war-related fears" operates within a highly charged social and political context, predominantly marked by tensions among global powers and the proliferation of military conflicts. It primarily centers around influential actors such as government officials, political commentators, and media outlets that are often engaged in amplifying concerns regarding impending warfare. The narrative employs emotionally charged language designed to provoke anxiety and paranoia in its audience, seeking to instill a sense of urgency and dread regarding potential conflicts, particularly the fear of escalation to nuclear warfare. These messages often imply that the actions of "the West"—or specific Western leaders—are catalyzing a dangerous escalation of global tensions, thereby intensifying societal fears about security and safety. The conclusions aimed at the reader typically revolve around the inevitable nature of conflict if current trajectories remain unchanged, urging a critical examination of political decisions and public awareness. Textually, the narrative utilizes stark, evocative phrases and rhetorical questions that heighten emotional responses, as well as metaphors that frame war as an almost certain, looming threat. These characteristics are intended to create a compelling urgency that encourages readers to reflect on their own security and the broader implications of geopolitical decisions.

 48%|████▊     | 10/21 [02:49<03:38, 19.83s/it]

**Description of the Subnarrative: Criticism of Climate Policies**

This narrative critically examines the current climate policies implemented by governments and organizations, emphasizing their perceived shortcomings and questioning their underlying motives. It emerges within a socio-political context where environmental issues are of paramount concern, yet public skepticism regarding the feasibility and efficacy of these initiatives is growing. Main actors in this narrative often include policymakers, environmental activists, economists, and industry leaders, each offering differing perspectives on the impact of climate strategies. The narrative seeks to evoke a mix of emotions, including frustration and concern among citizens who feel these policies may overlook practical implications, such as economic ramifications or job loss in traditional industries. The conclusions it encourages readers to draw often center around the idea that while climate change is an urgent issue, hastily implemented policies may lead to unintended consequences and should be carefully scrutinized. Textually, the narrative is characterized by a blend of factual statements, anecdotal evidence, and rhetorical questions that challenge the status quo, aiming to create a sense of urgency and provoke critical reflection among readers about the effectiveness and fairness of the climate policies in question.

 57%|█████▋    | 12/21 [03:22<02:47, 18.64s/it]

**Narrative Description:**

This subnarrative critically examines the perceived shortcomings of institutions and authorities in addressing climate change, focusing on their competence, integrity, and intentions. It highlights the social context of rising public concern regarding environmental degradation and the increasing urgency for effective climate action. Politically, the narrative positions itself against established governmental bodies and corporations, questioning their commitment to sustainable practices and climate policies. Key actors typically include environmental activists, scientists, political leaders, and representatives from NGOs, who express a range of emotions such as frustration, urgency, and hope—especially in advocating for accountability and reform. The message aims to provoke audiences to question the status quo and to foster a sense of collective responsibility towards environmental stewardship, pushing for transformative actions. The textual characteristics include compelling statistics, emotional appeals, and rhetorical questions, often employing a critical tone to engage readers critically with the failures and challenges posed by current frameworks in mitigating climate change challenges. Through this narrative, the reader is guided towards recognizing the implications of governmental and institutional negligence, ultimately culminating in a call for greater transparency and action in climate initiatives.

 62%|██████▏   | 13/21 [03:56<02:54, 21.81s/it]

In the narrative titled "Climate Change is Beneficial," various arguments are crafted to support the notion that certain aspects of climate change can yield positive outcomes. The narrative navigates the complex social, political, and economic contexts surrounding climate discourse, focusing particularly on specific groups or regions that may experience short-term advantages, such as increased agricultural yields in certain areas or economic opportunities in emerging markets harnessing renewable energy. It presents main actors including policymakers, environmental advocates, farmers, and business leaders, each offering a perspective on how climate change might be leveraged for economic growth or social advancement. Emotionally, the narrative aims to evoke feelings of optimism and hope, challenging prevailing pessimism about climate change by highlighting potential benefits and opportunities. Readers are encouraged to reconsider a binary view of climate change, leading them to conclusions that embrace a more nuanced understanding of environmental issues, where adaptation and innovation can play a significant role in framing future responses. Textually, the narrative may include persuasive language, anecdotal evidence, and statistical data to reinforce its claims, as well as counterarguments to bolster the position that not all consequences of climate change are detrimental.

 67%|██████▋   | 14/21 [04:31<02:54, 24.97s/it]

**Description of the Subnarrative: Downplaying Climate Change**

This subnarrative encapsulates the statements and rhetoric employed by various social, political, and economic actors—such as corporations, politicians, and influential media members—that aim to diminish the urgency and severity of climate change. In the current societal context, this discourse often emerges against a backdrop of increasing public concern over environmental degradation and its consequences, including extreme weather events and rising sea levels. The key actors involved include climate change skeptics, fossil fuel industries, and policymakers resistant to implementing sustainable practices, all of whom may stand to lose economically from stringent environmental regulations. The narrative seeks to evoke a sense of safety or optimism in readers, suggesting that climate change is either exaggerated or manageable without drastic action. Through selective use of data and cherry-picking scientific studies, it aims to downplay the consensus on climate science, ultimately encouraging complacency. The desired conclusions for the reader may include belief in the idea that immediate action is unnecessary, fostering a dangerous status quo. Textually, this subnarrative often features persuasive language, anecdotal evidence, and appeals to authority, while downplaying or dismissing contradictory scientific consensus, effectively shaping public perception around climate challenges.

 71%|███████▏  | 15/21 [05:05<02:43, 27.23s/it]

**Narrative Subdescription: Questioning the Measurements and Science**

This narrative centers on the growing skepticism surrounding the scientific methods employed in climate change research and the validity of its data. The social context reveals a divide between climate advocates and skeptics, with influential figures such as scientists, policy makers, and activists as key actors. Politically, the narrative may incite debates over climate policy, regulation, and funding for environmental initiatives, often aligning with conservative viewpoints that emphasize economic growth over environmental protections. Economically, it implies potential impacts on industries that could be affected by climate regulations, like fossil fuels and manufacturing.

The message seeks to evoke emotions such as confusion, mistrust, and urgency among readers, prompting them to question established scientific consensus and explore alternative narratives. The conclusions aimed for are a reconsideration of current climate policies and an endorsement of ongoing dialogue about scientific methodologies. Textually, the narrative may include persuasive language, anecdotal evidence, rhetorical questions, and references to controversies within the scientific community, designed to engage readers and encourage skepticism towards mainstream climate science.

 76%|███████▌  | 16/21 [05:39<02:24, 28.91s/it]

**Description of the Subnarrative: Criticism of Climate Movement**

This subnarrative critiques the climate movement, positioning it within a complex social and political context where scientific discourse, environmental activism, and public perception intersect. It involves key actors such as climate scientists, political leaders, environmental activists, and skeptics who challenge the prevailing narratives about climate change. The critique often emerges from individuals or groups who argue that alarmism and speculation regarding climate collapse overshadow genuine scientific debate and dissent. By questioning the motives and integrity of the climate movement, this narrative aims to evoke feelings of skepticism, doubt, and concern among readers. It challenges the notion that all criticism of climate change is invalid or harmful, instead suggesting that dissent is crucial for a balanced discourse. The overarching conclusions readers are encouraged to reach may include the belief that the climate movement is not monolithic and that it is essential to scrutinize its claims and methodologies critically. Textually, this narrative employs rhetorical techniques such as analogies, counterarguments, and emotive language to engage the audience, while also using concrete examples to bolster its claims about the scientific community and climate advocacy.

 81%|████████  | 17/21 [06:13<02:01, 30.26s/it]

**Narrative Title: Controversy about Green Technologies**

**Description:** The narrative surrounding "Controversy about Green Technologies" delves into the ongoing debates and discussions regarding the efficacy and impact of eco-friendly technologies on society and the environment. This subnarrative is set against a backdrop of escalating climate change concerns, heightened political discourse surrounding sustainability, and economic factors such as job creation versus technological displacement. Key actors in this narrative include environmental advocates, skeptics from various industries, government policymakers, and scientists. The tone may oscillate between critical skepticism and hopeful advocacy, aiming to provoke a mix of concern, interest, and possibly anger among readers who are passionate about environmental issues. The concluding message often encourages readers to question the sustainability of these technologies and the motives of those promoting them, ultimately urging a balanced understanding of both their potential benefits and drawbacks. The textual characteristics include persuasive language, the use of statistics to support claims, emotionally charged anecdotes, and a balanced presentation of opposing viewpoints, encouraging readers to engage deeply with the complexities of green technologies in contemporary discourse.

 86%|████████▌ | 18/21 [06:47<01:34, 31.36s/it]

**Subnarrative Description:**

This narrative delves into the intricate web of alleged clandestine operations orchestrated by influential political and corporate entities concerning climate change. The social context is marked by rising public awareness and anxiety about environmental degradation, fueling suspicions toward those in positions of authority. Politically, it examines the interplay between governmental policies and corporate lobbying, suggesting that powerful groups may prioritize profit over planet, often at the expense of transparency and accountability. Economically, it highlights the potential conflicts of interest that arise when profit-driven motives clash with sustainable practices. Key actors in this narrative include policymakers, corporate executives, environmental activists, and ordinary citizens caught in the crossfire of these high-stakes games. The narrative aims to evoke feelings of distrust and concern among readers, urging them to question the motivations behind climate action—or inaction—by powerful groups. Ultimately, it seeks to guide readers toward a conclusion that emphasizes the need for vigilance, advocacy, and systemic change to ensure that climate-related decisions prioritize the greater good over opaque agendas. Textually, the narrative is characterized by a tone of urgency and skepticism, employing evocative language to convey the complexity and gravity of the issues at hand, while integrating rhetorical questions and calls to action that engage the reader's critical thinking.

 90%|█████████ | 19/21 [07:21<01:04, 32.07s/it]

**Subnarrative Description: Amplifying Climate Fears**

This narrative unfolds within a broad social context marked by growing public awareness and concern over climate change. Politically, it engages various actors, including government officials, environmental organizations, scientists, and influential media outlets, all of whom play a pivotal role in shaping the discourse around climate fears. Economically, it touches upon the implications of climate change on industries, livelihoods, and global markets, often highlighting the urgency for sustainable practices and policies. Emotionally, the narrative is designed to provoke a sense of anxiety and urgency, instilling a fear of impending disasters such as natural catastrophes, resource scarcity, and societal upheaval. The underlying message encourages the reader to recognize the critical nature of climate challenges and to support advocacy for impactful climate action. Textually, this narrative utilizes vivid imagery and alarming statistics, employing persuasive language and emotional appeal to amplify its impact. The repetition of key terms related to urgency and threat, along with testimonies from experts and affected communities, reinforces the need for immediate attention and action regarding climate issues.

 95%|█████████▌| 20/21 [07:55<00:32, 32.66s/it]

**Subnarrative Description:**

In this narrative, the central theme revolves around the assertion that green policies—such as climate agreements, renewable energy initiatives, and biodiversity conservation strategies—are not merely expressions of environmental stewardship but rather strategic tools employed by nations to assert geopolitical power, influence international relations, and secure economic advantages. The social context encompasses a growing skepticism among the public regarding the sincerity of governmental and corporate commitments to sustainability, intertwining issues of climate justice with broader discussions about global inequalities. Politically, this narrative highlights key actors including powerful nations, international organizations, and influential corporations that may prioritize their own interests over genuine ecological concerns, thus raising questions about accountability and ethical leadership. Economically, it draws attention to how nations might leverage green initiatives to bolster trade relations, attract investments, or manipulate regulatory frameworks to their benefit. The emotions this message seeks to evoke include distrust, concern, and outrage over perceived hypocrisy, aiming to provoke critical reflection among readers about the motives behind environmental rhetoric. Ultimately, the narrative encourages readers to question the integrity of green policies, urging them to discern the underlying political and economic agendas at play. Textually, it employs persuasive language, rhetorical questioning, and examples of recent geopolitical maneuvers to reinforce its message, crafting a compelling and thought-provoking discourse on the intersection of environmental action and global power dynamics.

100%|██████████| 21/21 [08:29<00:00, 24.28s/it]

In [7]:
df_results

        id                                        description
0   URW5.2  The West Belongs on the Right Side of History*...
1    CC1.2  The subnarrative titled "Climate policies have...
2    CC6.1  This subnarrative critiques the climate moveme...
3   URW1.1  This subnarrative seeks to reframe the conflic...
4   URW1.2  This subnarrative presents a perspective that ...
..     ...                                                ...
90    CC6.  **Description of the Subnarrative: Criticism o...
91    CC7.  **Narrative Title: Controversy about Green Tec...
92    CC8.  **Subnarrative Description:**\n\nThis narrativ...
93    CC9.  **Subnarrative Description: Amplifying Climate...
94   CC10.  **Subnarrative Description:**\n\nIn this narra...

[95 rows x 2 columns]

In [8]:
name='gpt_z_s_desc_title_description_complete'
df_results.to_pickle(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}_v2.pkl')
df_results.to_json(f'/home/jfraile/Programs/SemEval_2025_T10_S2/description_generation/zero_shot_desc/{name}_v2.json', orient='records', indent=2, force_ascii=False)